/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.tutorial;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void Capitalize1() {
        HelloConsole app = new HelloConsole();
        assertEquals(app.Capitalize("testing capitalization in command line"),
                "Testing Capitalization In Command Line");
    }

    @Test
    void Capitalize2() {
        HelloConsole app = new HelloConsole();
        assertEquals(app.Capitalize("excitement replaced fear until the final moment"),
                "Excitement Replaced Fear Until The Final Moment");
    }

    @Test
    void Capitalize3() {
        HelloConsole app = new HelloConsole();
        assertEquals(app.Capitalize("I want more detailed information"),
                "I Want More Detailed Information");
    }

    @Test
    void Capitalize4() {
        HelloConsole app = new HelloConsole();
        assertEquals(app.Capitalize("Tuesdays are free if you bring a gnome costume"),
                "Tuesdays Are Free If You Bring A Gnome Costume");
    }
}
